config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, components: {registrations: 'users/registrations', sessions: 'users/sessions'}

  get '/step/get_completed_steps/:lesson_id', to: 'step#get_completed_steps'
  get '/step/complete_step/', to: 'step#complete_step'
  get '/step/get_next_step/', to: 'step#get_next_step'

  resources :course do
    resources :lesson, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
  has_many :steps
  has_one_attached :avatar
end

app/models/completed_lesson.rb
class CompletedLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/completed_step.rb
class CompletedStep < ApplicationRecord
  belongs_to :step
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :users, through: :subscriptions
  has_many :subscriptions
  has_many :lessons
  has_one_attached :image
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :completed_lessons
  has_many :steps

end

app/models/step.rb
class Step < ApplicationRecord
  serialize :content
  belongs_to :lesson
  has_many :completed_steps
  belongs_to :bot
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :courses, through: :subscriptions
  has_many :completed_lessons
  has_many :completed_steps
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name, :surname, :email, :phone, :avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @course = Course.find(params[:id])
    @lessons = @course.lessons.order(:tag)
    user_completed_lessons = current_user.completed_lessons.where({lesson_id: @lessons})
    if user_completed_lessons.count > 0
      last_completed_lesson_tag = @lessons.where({id: user_completed_lessons.pluck(:lesson_id)}).order(:tag).last.tag
      @active_lesson = Lesson.find_by tag: last_completed_lesson_tag + 1
    else
      @active_lesson = @lessons.first
    end

    if current_user.subscriptions.where(course_id: @course.id).count == 0
      Subscription.create!(course_id: @course.id, user_id: @user.id)
    end

    redirect_to proc {course_lesson_url(@course,@active_lesson)}
  end

  def index
    @courses = Course.all
  end

end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @course = Course.find(params[:course_id])
    @lessons = @course.lessons.order(:tag)
    @active_lesson = Lesson.find(params[:id])

    if @user.completed_lessons.where(lesson_id: @lessons).count > 0 then
      all_completed_lessons_of_user = @user.completed_lessons.where(lesson_id: @lessons.pluck(:id))
      last_completed_lesson_of_user = Lesson.where(id: all_completed_lessons_of_user.pluck(:lesson_id)).order(:tag).last

      if Lesson.find_by_tag(last_completed_lesson_of_user.tag + 1) then
        @last_lesson = Lesson.find_by_tag(last_completed_lesson_of_user.tag + 1)
      else
        @last_lesson = @active_lesson;
      end
    end

    @steps = @active_lesson.steps
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @courses = Course.all
  end
end

app/controllers/step_controller.rb
class StepController < ApplicationController

  #Функция получения завершенных шагов
  def get_completed_steps
    @lesson = Lesson.find(params[:lesson_id])
    @total_lessons = Course.find(@lesson.course_id).lessons.count
    @steps = @lesson.steps.where({id: current_user.completed_steps.pluck(:step_id)}).order(:tag)
    if !@steps.exists? then
      @steps = @lesson.steps.where({tag: 0})
      @step = @lesson.steps.first
      current_user.completed_steps.create!(step_id: @step.id, user_id: current_user.id)
    end

    render json: @steps, meta: {total_lessons: @total_lessons, current_lesson: @lesson ,total_steps: @lesson.steps.count, total_tests: @lesson.steps.where(step_type: ['test_input', 'test_option', 'test_checkbox']).count, user_name: current_user.name, user_avatar: current_user.avatar.attached? ? rails_blob_path(current_user.avatar, only_path: true) : nil}, root: "steps"

  end

# Функция завершения шага
  def complete_step
    respond_to do |format|
      format.json {
        @step = Step.find(params[:step_id])
        @lesson = Lesson.find_by_id(@step.lesson_id)
        @user = current_user
        if params.has_key?(:user_answer) then
          @user_answer = params[:user_answer]
          if @user_answer == @step.correctanswer
            @correct = true
          else
            @correct = false
          end
          request = @user.completed_steps.create!(step_id: @step.id, user_id: @user.id, useranswer: @user_answer, correct: @correct)
        else
          request = @user.completed_steps.create!(step_id: @step.id, user_id: @user.id)
        end

        if @user.completed_steps.where({step_id: @lesson.steps}).count == @lesson.steps.count
          @user.completed_lessons.create!(lesson_id: @lesson.id, user_id: @user.id, correctanswers: @user.completed_steps.where({step_id: @lesson.steps, correct: 1}).count)
          if @user.completed_lessons.find_by_lesson_id(@lesson.id).correctanswers != nil
            @correct_answers = @user.completed_lessons.find_by_lesson_id(@lesson.id).correctanswers
          else
            @correct_answers = nil
          end
        end

        if request
          render json: {status: 'ok', correct: @correct, correct_answers: @correct_answers}.to_json
        else
          render json: {status: 'error'}.to_json
        end
      }

     end

  end

# Функция получения следующего шага
  def get_next_step
    respond_to do |format|
      format.json {
        @current_step = Step.find(params[:current_step])
        @next_step = Step.find_by_tag(@current_step.tag + 1)
        render json: @next_step
      }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/step_helper.rb
module StepHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Simulator</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'botui.min.css' %>
    <%= stylesheet_link_tag    'botui-theme-default.css' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/vue/latest/vue.min.js"></script>
    <%= javascript_include_tag 'botui.js'%>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css" integrity="sha384-oS3vJWv+0UjzBfQzYUhtDYW+Pj2yciDJxpsK1OYPAYjqT085Qq/1cq5FLXAZQ7Ay" crossorigin="anonymous">
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= render partial: "shared/main_header" %>
<div class="container">
  <div class="row align-items-center">
    <div class="col-md-10 offset-md-1">
      <%= image_tag "graph.png", :class => 'mw-100 mb-5' %>
      <h1 class="text-center">Симулятор работы в маркетинговом агентстве</h1>
      <p class="text-center">Вы получите реальный опыт, выполняя клиентские
        задачи, анализируя реальные данные в системах аналитики, принимая
        решения.
      </p>
    </div>
  </div>
</div>

<%= render partial: "shared/main_footer" %>

app/views/shared/_main_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.jpg", class: "d-inline-block", "width": "30", "height": "30" %>
    Simulator
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <%= link_to "Главная", root_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
  <% if user_signed_in? %>
    <%= link_to 'Открыть курсы', course_index_path, :class => 'btn btn-primary' %>
  <% else %>
    <%= link_to 'Войти', new_user_session_path, :class => 'btn btn-primary m-1' %>
    <%= link_to 'Регистрация', new_user_registration_path, :class => 'btn btn-success m-1' %>
  <% end %>
</nav>

app/views/shared/_simulator_header.html.erb
<div class="d-none d-md-block col-md-1">
  <!-- ЛОГО СЛЕВА -->
  <div class="float-group left">
    <div class="float-btn">
      <%= link_to root_path do %>
        <%= image_tag 'logo.jpg'%>
      <% end %>
    </div>
  </div>

  <div class="float-group right" id="menubtn">
    <div class="float-btn" id="sidebarCollapse">
      <i class="fa fa-bars mr-2"></i>
    </div>
  </div>

  <!-- Меню справа -->
  <div class="vertical-nav active" id="sidebar">
    <div id="profile-menu">
      <div class="logout-link">
        <%= link_to destroy_user_session_path, method: :delete do %>
          <i class="fas fa-sign-out-alt"></i>
        <% end %>
      </div>
      <div class="profile-link">
        <%= link_to edit_user_registration_path, :"data-turbolinks" => false do %>
          <i class="fas fa-user-cog"></i>
        <% end %>
      </div>
      <div class="name">
        <div class="avatar">
          <%= @user.name[0,1] %><%= @user.surname[0,1] %>
        </div>
        <span class="username">
          <%= @user.name %> <%= @user.surname %>
        </span>
      </div>
    </div>

    <div id="toc-menu">
      <h2>Главы курса "<%= @course.name %>"</h2>
      <ul class="chapters">
        <% @lessons.each do |lesson| %>
          <li class="<% if lesson == @active_lesson or lesson == @last_lesson  %> active <% elsif current_user.completed_lessons.find_by_lesson_id(lesson.id) %> FINISHED <% end %>">
            <span class="num"><%= lesson.tag + 1 %>.</span>
            <% if lesson == @active_lesson or lesson == @last_lesson or current_user.completed_lessons.find_by_lesson_id(lesson.id) %>
              <%= link_to lesson.name, [@course,lesson], "data-turbolinks": "false" %>
            <% else %>
              <%= lesson.name %>
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>

  </div>
</div>

<script type="text/javascript">
  $(function() {
  // Sidebar toggle behavior
  $('#sidebarCollapse').on('click', function() {
    $('#sidebar, #content, #menubtn').toggleClass('active');
  });
});
</script>