config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, components: {registrations: 'users/registrations', sessions: 'users/sessions'}

  get '/step/get_completed_steps/:lesson_id', to: 'step#get_completed_steps'
  get '/step/complete_step/', to: 'step#complete_step'
  get '/step/get_next_step/', to: 'step#get_next_step'

  resources :course do
    resources :lesson, only: [:show]
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bot.rb
class Bot < ApplicationRecord
  has_many :steps
  has_one_attached :avatar
end

app/models/completed_lesson.rb
class CompletedLesson < ApplicationRecord
  belongs_to :lesson
  belongs_to :user
end

app/models/completed_step.rb
class CompletedStep < ApplicationRecord
  belongs_to :step
  belongs_to :user
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :users, through: :subscriptions
  has_many :subscriptions
  has_many :lessons
  has_one_attached :image
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :course
  has_many :completed_lessons
  has_many :steps

end

app/models/step.rb
class Step < ApplicationRecord
  serialize :content
  belongs_to :lesson
  has_many :completed_steps
  belongs_to :bot
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  belongs_to :course
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :subscriptions
  has_many :courses, through: :subscriptions
  has_many :completed_lessons
  has_many :completed_steps
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    attributes = [:name, :surname, :email, :phone, :avatar]
    devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
    devise_parameter_sanitizer.permit(:account_update, keys: attributes)
  end

end

app/controllers/concerns/response.rb
module Response
  def json_response(object, status = :ok)
    render json: object, status: status
  end
end

app/controllers/course_controller.rb
class CourseController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @course = Course.find(params[:id])
    @lessons = @course.lessons.order(:tag)
    user_completed_lessons = current_user.completed_lessons.where({lesson_id: @lessons})
    if user_completed_lessons.count > 0
      last_completed_lesson_tag = @lessons.where({id: user_completed_lessons.pluck(:lesson_id)}).order(:tag).last.tag
      @active_lesson = Lesson.find_by tag: last_completed_lesson_tag + 1
    else
      @active_lesson = @lessons.first
    end

    if current_user.subscriptions.where(course_id: @course.id).count == 0
      Subscription.create!(course_id: @course.id, user_id: @user.id)
    end

    redirect_to proc {course_lesson_url(@course,@active_lesson)}
  end

  def index
    @courses = Course.all
  end

end

app/controllers/lesson_controller.rb
class LessonController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @course = Course.find(params[:course_id])
    @lessons = @course.lessons.order(:tag)
    @active_lesson = Lesson.find(params[:id])

    if @user.completed_lessons.where(lesson_id: @lessons).count > 0 then
      all_completed_lessons_of_user = @user.completed_lessons.where(lesson_id: @lessons.pluck(:id))
      last_completed_lesson_of_user = Lesson.where(id: all_completed_lessons_of_user.pluck(:lesson_id)).order(:tag).last

      if Lesson.find_by_tag(last_completed_lesson_of_user.tag + 1) then
        @last_lesson = Lesson.find_by_tag(last_completed_lesson_of_user.tag + 1)
      else
        @last_lesson = @active_lesson;
      end
    end

    @steps = @active_lesson.steps
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @courses = Course.all
  end
end

app/controllers/step_controller.rb
class StepController < ApplicationController

  #Функция получения завершенных шагов
  def get_completed_steps
    @lesson = Lesson.find(params[:lesson_id])
    @total_lessons = Course.find(@lesson.course_id).lessons.count
    @steps = @lesson.steps.where({id: current_user.completed_steps.pluck(:step_id)}).order(:tag)
    if !@steps.exists? then
      @steps = @lesson.steps.where({tag: 0})
      @step = @lesson.steps.first
      current_user.completed_steps.create!(step_id: @step.id, user_id: current_user.id)
    end

    render json: @steps, meta: {total_lessons: @total_lessons, current_lesson: @lesson ,total_steps: @lesson.steps.count, total_tests: @lesson.steps.where(step_type: ['test_input', 'test_option', 'test_checkbox']).count, user_name: current_user.name, user_avatar: current_user.avatar.attached? ? rails_blob_path(current_user.avatar, only_path: true) : nil}, root: "steps"

  end

# Функция завершения шага
  def complete_step
    respond_to do |format|
      format.json {
        @step = Step.find(params[:step_id])
        @lesson = Lesson.find_by_id(@step.lesson_id)
        @user = current_user
        if params.has_key?(:user_answer) then
          @user_answer = params[:user_answer]
          if @user_answer == @step.correctanswer
            @correct = true
          else
            @correct = false
          end
          request = @user.completed_steps.create!(step_id: @step.id, user_id: @user.id, useranswer: @user_answer, correct: @correct)
        else
          request = @user.completed_steps.create!(step_id: @step.id, user_id: @user.id)
        end

        if @user.completed_steps.where({step_id: @lesson.steps}).count == @lesson.steps.count
          @user.completed_lessons.create!(lesson_id: @lesson.id, user_id: @user.id, correctanswers: @user.completed_steps.where({step_id: @lesson.steps, correct: 1}).count)
          if @user.completed_lessons.find_by_lesson_id(@lesson.id).correctanswers != nil
            @correct_answers = @user.completed_lessons.find_by_lesson_id(@lesson.id).correctanswers
          else
            @correct_answers = nil
          end
        end

        if request
          render json: {status: 'ok', correct: @correct, correct_answers: @correct_answers}.to_json
        else
          render json: {status: 'error'}.to_json
        end
      }

     end

  end

# Функция получения следующего шага
  def get_next_step
    respond_to do |format|
      format.json {
        @current_step = Step.find(params[:current_step])
        @next_step = Step.find_by_tag(@current_step.tag + 1)
        render json: @next_step
      }
    end
  end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   def new
     @courses = Course.all
   end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/step_helper.rb
module StepHelper
end

app/views/lesson/show.html.erb
<%= render partial: "shared/simulator_header" %>
<main id="chapter" class="front-task-section">
  <div class="page-content" id="content">
    <div class="container">
      <h1 class="chapter-title"><span><%= @active_lesson.tag + 1 %>. </span><%= @active_lesson.name %></h1>
      <div id="my-botui-app">
        <bot-ui></botui>
      </div>
      <div class="next-interactive">
        <a id = "next_step">Далее</a>
      </div>

    </div>

  </div>
</main>

<script type="text/javascript">

  var botui = new BotUI('my-botui-app');
  var current_step_id;
  var current_step_tag;
  var current_lesson;
  var total_lessons;
  var steps_count;
  var user_name;

  $.ajax({
    url: '/step/get_completed_steps/<%= @active_lesson.id %>',
    crossorigin: true,
    type: 'GET',
    dataType: 'JSON',
    success: function (data){
      console.log(data);
      steps_count = data['meta']['total_steps'];
      current_lesson = data['meta']['current_lesson']['tag'];
      total_lessons = data['meta']['total_lessons'];
      user_name = data['meta']['user_name'];
      user_avatar = data['meta']['user_avatar'];

      for (i = 0; i < data['steps'].length; i++){
        current_step_id = data['steps'][i]['id'];
        current_step_tag = data['steps'][i]['tag'];
        CheckForLastLesson();

        switch(data['steps'][i]['step_type']){
            case 'test_radio':
              var options = '';
              for (j=1; j<8; j++ ){
                if (data['steps'][i]['option'+j]){
                  options += j + '. ' + data['steps'][i]['option'+j] + '<br>';
                };
              };
              botui.message.add({
                photo: data['steps'][i]['bot'] ? data['steps'][i]['bot']['avatar_url'] : false,
                type: 'html',
                content: data['steps'][i]['content'] + '<br>' + options
              }).then(function(){
                CheckForUsername();
              });
              break;

            case 'test_checkbox':
              var options = '';
              for (j=1; j<8; j++ ){
                if (data['steps'][i]['option'+j]){
                  options += j + '. ' + data['steps'][i]['option'+j] + '<br>';
                };
              };
              botui.message.add({
                photo: data['steps'][i]['bot'] ? data['steps'][i]['bot']['avatar_url'] : false,
                type: 'html',
                content: data['steps'][i]['content'] + '<br>' + options
              }).then(function(){
                CheckForUsername();
              });
              break;

            default:
              botui.message.add({
                photo: data['steps'][i]['bot'] ? data['steps'][i]['bot']['avatar_url'] : false,
                type: 'html',
                content: data['steps'][i]['content']
              }).then(function(){
                CheckForUsername();
              });
              break;
        };

        if (data['steps'][i]['completed_steps'][0]['useranswer']){
          var user_answer = data['steps'][i]['completed_steps'][0]['useranswer'];
          var correct = data['steps'][i]['completed_steps'][0]['correct'];
          var message_if_correct = data['steps'][i]['message_if_correct'];
          var message_if_incorrect = data['steps'][i]['message_if_incorrect'];
          botui.message.add({
            photo: user_avatar ? user_avatar : false,
            human: true,
            type: 'html',
            content: user_answer
          });

          if (correct){
            botui.message.add({
              photo: data['steps'][i]['bot'] ? data['steps'][i]['bot']['avatar_url'] : false,
              cssClass: 'correct-answer',
              type: 'html',
              content: message_if_correct
            });
          } else{
            botui.message.add({
              photo: data['steps'][i]['bot'] ? data['steps'][i]['bot']['avatar_url'] : false,
              cssClass: 'incorrect-answer',
              type: 'html',
              content: message_if_incorrect
            });
          };
        }
      }
    },
    error: function (jqxhr, textStatus, error){
      var err = textStatus + ", " + error;
      console.log( "Request Failed: " + err);
    }
  });

</script>

<script type="text/javascript">

  function CheckForLastLesson(){
    if (current_step_tag == steps_count - 1){
      if (current_lesson + 1 != total_lessons){
        $('#next_step').text('Перейти к следующему уроку').attr('href','<%= course_lesson_path(@course, Lesson.find_by_tag(@active_lesson.tag + 1)) %>').off('click');
      } else{
        $('#next_step').remove();
      }
    }
  };

  function CheckForUsername(){
    $('.user_name').html(user_name);
  };

  function CompleteStep(step_id, user_answer){
    var response;
    $.ajax({
      url: '/step/complete_step/',
      crossorigin: true,
      type: 'GET',
      dataType: 'JSON',
      async: false,
      data: {
        step_id: step_id,
        user_answer: user_answer
      },
      success: function (data){
        console.log(data);
        response = data['correct'];
      },
      error: function (jqxhr, textStatus, error){
        var err = textStatus + ", " + error;
        console.log( "Request Failed: " + err);
      }
    });

    return response;
  };

  $('#next_step').on('click', function(){
    $.ajax({
      url: '/step/get_next_step/',
      crossorigin: true,
      type: 'GET',
      dataType: 'JSON',
      data: {
        current_step: current_step_id
      },
      success: function (data){
        console.log(data);
        current_step_id = data['step']['id'];
        current_step_tag = data['step']['tag'];

        switch (data['step']['step_type']){

          case 'message':
            CompleteStep(current_step_id);
            botui.message.add({
              photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
              loading: true,
              delay: data['step']['content'].length,
              type: 'html',
              content: data['step']['content']
            });
            CheckForLastLesson();
            CheckForUsername();
            break;

          case 'test_input':
            $('#next_step').hide();
            var message_if_correct = data['step']['message_if_correct'];
            var message_if_incorrect = data['step']['message_if_incorrect'];
            botui.message.add({
              photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
              loading: true,
              delay: data['step']['content'].length,
              type: 'html',
              content: data['step']['content']
            }).then(function(){
              CheckForUsername();
            });
            botui.action.text({
              action: {
                placeholder: 'Введите свой ответ'
              }
            }).then(function (res){
              var correct = CompleteStep(current_step_id, res.value);
              if (correct){
                botui.message.add({
                  photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'correct-answer',
                  type: 'html',
                  content: message_if_correct
                });
              } else{
                botui.message.add({
                  photo: data['steps']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'incorrect-answer',
                  type: 'html',
                  content: message_if_incorrect
                });
              };
            }).then(function(){
              $('#next_step').show();
              CheckForLastLesson();
            });
            break;

          case 'test_radio':
            $('#next_step').hide();
            var message_if_correct = data['step']['message_if_correct'];
            var message_if_incorrect = data['step']['message_if_incorrect'];
            botui.message.add({
              photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
              loading: true,
              delay: data['step']['content'].length,
              type: 'html',
              content: data['step']['content']
            }).then(function(){
              CheckForUsername();
            });
            var options = [];
            for (j=1;j<8;j++){
              if (data['step']['option'+j]){
                options.push({
                  text: data['step']['option'+j],
                  value: data['step']['option'+j]
                });
              };
            };
            botui.action.button({
              action: options
            }).then(function (res){
              var correct = CompleteStep(current_step_id, res.value);
              if (correct){
                botui.message.add({
                  photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'correct-answer',
                  type: 'html',
                  content: message_if_correct
                });
              } else{
                botui.message.add({
                  photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'incorrect-answer',
                  type: 'html',
                  content: message_if_incorrect
                });
              };
            }).then(function(){
              $('#next_step').show();
              CheckForLastLesson();
            });
            break;

          case 'test_checkbox':
            $('#next_step').hide();
            var message_if_correct = data['step']['message_if_correct'];
            var message_if_incorrect = data['step']['message_if_incorrect'];
            botui.message.add({
              photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
              loading: true,
              delay: data['step']['content'].length,
              type: 'html',
              content: data['step']['content']
            }).then(function(){
              CheckForUsername();
            });
            var options = [];
            for (j=1;j<8;j++){
              if (data['step']['option'+j]){
                options.push({
                  text: data['step']['option'+j],
                  value: data['step']['option'+j]
                });
              };
            };
            botui.action.select({
              action: {
                placeholder: "Выберите варианты ответов",
                multipleselect: true,
                options: options,
                button: {
                  icon: 'check',
                  label: 'OK'
                }
              }
            }).then(function (res){
              var correct = CompleteStep(current_step_id, res.value);
              if (correct){
                botui.message.add({
                  photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'correct-answer',
                  type: 'html',
                  content: message_if_correct
                });
              } else{
                botui.message.add({
                  photo: data['step']['bot'] ? data['step']['bot']['avatar_url'] : false,
                  cssClass: 'incorrect-answer',
                  type: 'html',
                  content: message_if_incorrect
                });
              };
            }).then(function(){
              $('#next_step').show();
              CheckForLastLesson();
            });
            break;

        };
      },
      error: function (jqxhr, textStatus, error){
        var err = textStatus + ", " + error;
        console.log( "Request Failed: " + err);
      }
    });
  });

</script>